name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - 'feature/*'
  pull_request:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      # Login only for staging + main
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push staging image
      - name: Build & Push Staging Image
        if: github.ref == 'refs/heads/staging'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product-api:staging -f ProductDemo/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-api:staging

      # Build & push production image
      - name: Build & Push Prod Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product-api:latest -f ProductDemo/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-api:latest